
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int ELSE = 18;
  public static final int SEMICOLON = 2;
  public static final int RIGHTBRACKET = 16;
  public static final int EQUAL = 4;
  public static final int NOTEQUAL = 6;
  public static final int LEFTPAR = 11;
  public static final int IDENTIFIER = 19;
  public static final int GREATER = 9;
  public static final int IF = 17;
  public static final int RIGHTPAR = 12;
  public static final int LESSEQUAL = 8;
  public static final int EQUALTO = 5;
  public static final int STRING = 20;
  public static final int EOF = 0;
  public static final int LEFTBRACKET = 15;
  public static final int error = 1;
  public static final int LEFTBRACE = 13;
  public static final int RIGHTBRACE = 14;
  public static final int GREATEREQUAL = 10;
  public static final int VAR = 3;
  public static final int LESS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "VAR",
  "EQUAL",
  "EQUALTO",
  "NOTEQUAL",
  "LESS",
  "LESSEQUAL",
  "GREATER",
  "GREATEREQUAL",
  "LEFTPAR",
  "RIGHTPAR",
  "LEFTBRACE",
  "RIGHTBRACE",
  "LEFTBRACKET",
  "RIGHTBRACKET",
  "IF",
  "ELSE",
  "IDENTIFIER",
  "STRING"
  };
}

