
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int LETRA = 6;
  public static final int MAIS = 3;
  public static final int PTVIRG = 2;
  public static final int error = 1;
  public static final int MENOS = 4;
  public static final int EOF = 0;
  public static final int SELECT = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTVIRG",
  "MAIS",
  "MENOS",
  "SELECT",
  "LETRA"
  };
}

